#!/usr/local/bin/python2.7
#chkconfig: 345 99 10
#description: SIMBA Data Service.

import sys, time, syslog
sys.path.append('/opt/thrift/dataservice/simba')

from datadaemon import DataDaemon


if __name__ == "__main__":
    daemon = DataDaemon('/tmp/DataDaemon.pid')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            print 'Starting SIMBA Data Service...'
            syslog.syslog('Starting SIMBA Data Service...')
            daemon.start()
        elif 'stop' == sys.argv[1]:
            print 'Stopping SIMBA Data Service...'
            syslog.syslog('Stopping SIMBA Data Service...')
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            print 'Restarting SIMBA Data Service...'
            syslog.syslog('Restarting SIMBA Data Service...')
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
            sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)

