#!/usr/bin/env python

import sys, time, syslog
sys.path.append('../')

from simba.cachedaemon import CacheDaemon


if __name__ == "__main__":
        daemon = CacheDaemon('/tmp/CacheDaemon.pid')
        if len(sys.argv) == 2:
                if 'start' == sys.argv[1]:
                        print 'Starting the server...'
						syslog.syslog('Starting the server...')
                        daemon.start()
                elif 'stop' == sys.argv[1]:
						print 'Stopping the server...'
                        syslog.syslog('Stopping the server...')
                        daemon.stop()
                elif 'restart' == sys.argv[1]:
						print 'Restarting the server...'
                        syslog.syslog('Restarting the server...')
                        daemon.restart()
                else:
                        print "Unknown command"
                        sys.exit(2)
                sys.exit(0)
        else:
                print "usage: %s start|stop|restart" % sys.argv[0]
                sys.exit(2)
