#!/usr/local/bin/python2.7
#chkconfig: 345 99 10
#description: SIMBA Metadata Service.

import sys, time, syslog
sys.path.append('/opt/thrift/metadataservice/')

from simba.metadatadaemon import MetadataDaemon


if __name__ == "__main__":
    daemon = MetadataDaemon('/tmp/MetadataDaemon.pid')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            print 'Starting SIMBA Metadata Service...'
            syslog.syslog('Starting SIMBA Metadata Service...')
            daemon.start()
        elif 'stop' == sys.argv[1]:
            print 'Stopping SIMBA Metadata Service...'
            syslog.syslog('Stopping SIMBA Metadata Service...')
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            print 'Restarting SIMBA Metadata Service...'
            syslog.syslog('Restarting SIMBA Metadata Service...')
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)

